/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import DAO.ImpDAOProducto;
import clases.Producto;
import clases.Usuario;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class BusquedaNombre extends javax.swing.JFrame {

   private Usuario usuario;
   private final ImpDAOProducto productoDAO = new ImpDAOProducto();
    public BusquedaNombre(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelProductos = new javax.swing.JPanel();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        jPanel1.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 450, 50));

        btnBuscar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 110, 50));

        panelProductos.setBackground(new java.awt.Color(255, 255, 255));
        panelProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelProductos.setFocusCycleRoot(true);
        panelProductos.setInheritsPopupMenu(true);
        panelProductos.setLayout(new javax.swing.BoxLayout(panelProductos, javax.swing.BoxLayout.LINE_AXIS));
        panelProductos.setLayout(new javax.swing.BoxLayout(panelProductos, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panelProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 750, 290));

        botonVolver.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       try {
           List<Producto> encontrados = productoDAO.buscarNombre(txtBusqueda.getText());
           int i = 1;
            if(!encontrados.isEmpty()){
                for(Producto prod : encontrados ){
                    ItemProducto item = new ItemProducto(prod);
                    System.out.println(prod);
                    panelProductos.add(item);
                    if((i%2)==0){
                        JPanel panel = item.getPanelPrincipal();
                        panel.setBackground(panel.getBackground().brighter());
                    }
                    i++;
                
            }    
            }else{
                JOptionPane.showMessageDialog(jPanel1, "No se encontraron productos que coincidan con lo ingresado");

            }
           
           panelProductos.revalidate();
           
       } catch (SQLException | ClassNotFoundException ex) {
                       JOptionPane.showMessageDialog(jPanel1, "No se pudo conectar con la base de datos" + ex.getMessage());

       }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        int tipoUsuario = usuario.getIdTipo();
        switch(tipoUsuario){
            case 1:
            InterfazAdmin interAdmin = new InterfazAdmin (usuario);
            interAdmin.setVisible(true);
            this.setVisible(false);
            break;
            case 2:
            InterfazUsuario interUsu = new InterfazUsuario (usuario);
            interUsu.setVisible(true);
            this.setVisible(false);
            break;
        }
    }//GEN-LAST:event_botonVolverActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        
    }//GEN-LAST:event_txtBusquedaActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolver;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

}
