/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package igu;

import DAO.ImpDAOEstadoEntrega;
import clases.EstadoEntrega;
import clases.Pedido;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mauri
 */
public class ItemPedido extends javax.swing.JPanel {
        private final Pedido pedido; 
        private final ImpDAOEstadoEntrega estadoEntregaDAO= new ImpDAOEstadoEntrega();
    public ItemPedido(Pedido ped) {
        this.pedido = ped;
        initComponents();
        rellenarPedido();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        lblEntregaEstim = new javax.swing.JLabel();
        lblFechaPed = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.BorderLayout());

        lblNumero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumero.setText("Numero del pedido");

        lblEntregaEstim.setText("Entrega estimada:");

        lblFechaPed.setText("Realizado el:");

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEstado.setText("EstadoEntrega");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblFechaPed, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEntregaEstim, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(lblEstado)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(lblEstado))
                .addGap(12, 12, 12)
                .addComponent(lblFechaPed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEntregaEstim)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        add(panelPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEntregaEstim;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaPed;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblEntregaEstim() {
        return lblEntregaEstim;
    }

    public JLabel getLblEstado() {
        return lblEstado;
    }

    public JLabel getLblFechaPed() {
        return lblFechaPed;
    }

    public JLabel getLblNumero() {
        return lblNumero;
    }

    public JPanel getPanelPrincipal() {
        return panelPrincipal;
    }

    
    
    private void rellenarPedido() {
        
            try {
                EstadoEntrega estado = estadoEntregaDAO.obtener(pedido.getIdEstado());
                lblEstado.setText(estado.getDescripcion());
                
                switch(estado.getIdEstado()){
                    case 8 -> lblEstado.setForeground(Color.red);
                    case 7 -> lblEstado.setForeground(Color.yellow);
                    case 6 -> lblEstado.setForeground(Color.blue);
                    case 5 -> lblEstado.setForeground(Color.green);
                }
                
                
                
                String entregaEstimada = pedido.getEntregaEstimada().toString();
                String fechaPedido = pedido.getFechaPedido().toString();
                lblFechaPed.setText(lblFechaPed.getText()+" " + fechaPedido);
                lblEntregaEstim.setText(lblEntregaEstim.getText()+" "+ entregaEstimada);
                lblNumero.setText("Pedido con ID: " + pedido.getIdPedido());
                
                
            } catch (SQLException | ClassNotFoundException ex) {
                lblNumero.setText("NO SE PUDIERON OBTENER DATOS DEL PEDIDO");
                JOptionPane.showMessageDialog(jPanel1, ex.toString());

            }
        
        
        
        
        
        
    }
    
    

}
