/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import DAO.ImpDAOPedido;
import clases.Pedido;
import clases.Usuario;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class ListaPedidosAdmin extends javax.swing.JFrame {
    private Usuario usuario;
    private final ImpDAOPedido pedidoDAO = new ImpDAOPedido();

    public ListaPedidosAdmin(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        completarLista();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        scrollPedidos = new javax.swing.JScrollPane();
        panelPedidos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 110, 40));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 100, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 50, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 150, 10));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("LISTA DE PEDIDOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 330, -1));

        panelPedidos.setBackground(new java.awt.Color(255, 255, 255));
        panelPedidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelPedidos.setFocusCycleRoot(true);
        panelPedidos.setInheritsPopupMenu(true);
        panelPedidos.setLayout(new javax.swing.BoxLayout(panelPedidos, javax.swing.BoxLayout.LINE_AXIS));
        panelPedidos.setLayout(new javax.swing.BoxLayout(panelPedidos, javax.swing.BoxLayout.Y_AXIS));
        scrollPedidos.setViewportView(panelPedidos);

        jPanel1.add(scrollPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 770, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                  int tipoUsuario = usuario.getIdTipo();
              switch(tipoUsuario){
                  case 1:
                      InterfazAdmin interAdmin = new InterfazAdmin (usuario);
                      interAdmin.setVisible(true);
                     this.setVisible(false);
                      break;
                  case 2:
                      InterfazUsuario interUsu = new InterfazUsuario (usuario);
                      interUsu.setVisible(true);
                       this.setVisible(false);
                     break; 
              }
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel panelPedidos;
    private javax.swing.JScrollPane scrollPedidos;
    // End of variables declaration//GEN-END:variables

    private void completarLista() {
        try {
            List<Pedido> pedidos = pedidoDAO.listar();
            Integer i = 1;
            
            if(!pedidos.isEmpty()){
                for(Pedido ped : pedidos){
                    ItemPedido item = new ItemPedido(ped);
                    panelPedidos.add(item);
                    JLabel numeroPed = item.getLblNumero();
                    linkear(numeroPed, ped, this);
                    if((i%2)==0){
                        JPanel panel = item.getPanelPrincipal();
                        panel.setBackground(panel.getBackground().brighter());
                    }
                    i++;
                }
            }else{
                JOptionPane.showMessageDialog(this, "No se realizaron pedidos");
            }
            
            panelPedidos.revalidate();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos "+ex.getMessage());
        }
    }

    private void linkear(JLabel label, Pedido ped, ListaPedidosAdmin vent) {
        Color letraOriginal = label.getForeground();
        
        label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) { 
                label.setForeground(new Color(70, 130, 180)); 
                label.setCursor(new Cursor(Cursor.HAND_CURSOR)); 
            }

            @Override
            public void mouseExited(MouseEvent e) {
                label.setForeground(letraOriginal); 
                label.setCursor(new Cursor(Cursor.DEFAULT_CURSOR)); 
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                InterfazPedido intProd = new InterfazPedido(usuario, ped);
                intProd.setVisible(true);
                vent.setVisible(false);
            }
        });


    }
}
