/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.awt.Color;

/**
 *
 * @author Nacho
 */
public class ProductoNuevo extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUsuario
     */
    public ProductoNuevo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtCantStock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCTO NUEVO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 450, 90));

        jLabel2.setText("CATEGORIA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        jLabel3.setText("NOMBRE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 60, -1));

        jLabel5.setText("PRECIO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel6.setText("CANTIDAD EN STOCK");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("Ingrese el nombre del producto");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 180, 20));

        txtPrecio.setForeground(new java.awt.Color(204, 204, 204));
        txtPrecio.setText("Ingrese el precio del producto");
        txtPrecio.setBorder(null);
        txtPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPrecioMousePressed(evt);
            }
        });
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 170, -1));

        txtCategoria.setForeground(new java.awt.Color(204, 204, 204));
        txtCategoria.setText("Ingrese una categoria");
        txtCategoria.setBorder(null);
        txtCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCategoriaMousePressed(evt);
            }
        });
        txtCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 170, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 170, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 170, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 170, 10));

        txtCantStock.setForeground(new java.awt.Color(204, 204, 204));
        txtCantStock.setText("Ingrese la cantidad en stock");
        txtCantStock.setBorder(null);
        txtCantStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCantStockMousePressed(evt);
            }
        });
        txtCantStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantStockActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 170, -1));

        jLabel4.setText("CATEGORIA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 170, 10));

        jLabel7.setText("DESCRIPCION");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        txtDescripcion.setForeground(new java.awt.Color(204, 204, 204));
        txtDescripcion.setText("Ingrese una descripcion");
        txtDescripcion.setBorder(null);
        txtDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDescripcionMousePressed(evt);
            }
        });
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 170, 20));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 170, 10));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaActionPerformed

    private void txtCantStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantStockActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
          if(txtUsuario.getText().equals("Ingrese el nombre del producto")){
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.black);
        }
        
      if(txtPrecio.getText().isEmpty()){
          txtPrecio.setText("Ingrese el precio del producto");
          txtPrecio.setForeground(Color.gray);
      }
      if(txtCantStock.getText().isEmpty()){
          txtCantStock.setText("Ingrese la cantidad en stock");
          txtCantStock.setForeground(Color.gray);
      }
      if(txtCategoria.getText().isEmpty()){
          txtCategoria.setText("Ingrese una categoria");
          txtCategoria.setForeground(Color.gray);
      }
      if(txtDescripcion.getText().isEmpty()){
          txtDescripcion.setText("Ingrese una descripcion");
          txtDescripcion.setForeground(Color.gray);
      }
      
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtPrecioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioMousePressed
               if(txtPrecio.getText().equals("Ingrese el precio del producto")){
            txtPrecio.setText("");
            txtPrecio.setForeground(Color.black);
        }
        
      if(txtUsuario.getText().isEmpty()){
          txtUsuario.setText("Ingrese el nombre del producto");
          txtUsuario.setForeground(Color.gray);
      }
      if(txtCantStock.getText().isEmpty()){
          txtCantStock.setText("Ingrese la cantidad en stock");
          txtCantStock.setForeground(Color.gray);
      }
      if(txtCategoria.getText().isEmpty()){
          txtCategoria.setText("Ingrese una categoria");
          txtCategoria.setForeground(Color.gray);
      }
      if(txtDescripcion.getText().isEmpty()){
          txtDescripcion.setText("Ingrese una descripcion");
          txtDescripcion.setForeground(Color.gray);
      }
      
    }//GEN-LAST:event_txtPrecioMousePressed

    private void txtCantStockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantStockMousePressed
       if(txtCantStock.getText().equals("Ingrese la cantidad en stock")){
            txtCantStock.setText("");
            txtCantStock.setForeground(Color.black);
        }
        
      if(txtPrecio.getText().isEmpty()){
          txtPrecio.setText("Ingrese el precio del producto");
          txtPrecio.setForeground(Color.gray);
      }
      if(txtUsuario.getText().isEmpty()){
          txtUsuario.setText("Ingrese el nombre del producto");
          txtUsuario.setForeground(Color.gray);
      }
      if(txtCategoria.getText().isEmpty()){
          txtCategoria.setText("Ingrese una categoria");
          txtCategoria.setForeground(Color.gray);
      }
      if(txtDescripcion.getText().isEmpty()){
          txtDescripcion.setText("Ingrese una descripcion");
          txtDescripcion.setForeground(Color.gray);
      }
      
    }//GEN-LAST:event_txtCantStockMousePressed

    private void txtCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCategoriaMousePressed
     if(txtCategoria.getText().equals("Ingrese una categoria")){
            txtCategoria.setText("");
            txtCategoria.setForeground(Color.black);
        }
        
      if(txtPrecio.getText().isEmpty()){
          txtPrecio.setText("Ingrese el precio del producto");
          txtPrecio.setForeground(Color.gray);
      }
      if(txtCantStock.getText().isEmpty()){
          txtCantStock.setText("Ingrese la cantidad en stock");
          txtCantStock.setForeground(Color.gray);
      }
      if(txtUsuario.getText().isEmpty()){
          txtUsuario.setText("Ingrese el nombre del producto");
          txtUsuario.setForeground(Color.gray);
      }
      if(txtDescripcion.getText().isEmpty()){
          txtDescripcion.setText("Ingrese una descripcion");
          txtDescripcion.setForeground(Color.gray);
      }
      
    }//GEN-LAST:event_txtCategoriaMousePressed

    private void txtDescripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescripcionMousePressed
           if(txtDescripcion.getText().equals("Ingrese una descripcion")){
            txtDescripcion.setText("");
            txtDescripcion.setForeground(Color.black);
        }
        
      if(txtPrecio.getText().isEmpty()){
          txtPrecio.setText("Ingrese el precio del producto");
          txtPrecio.setForeground(Color.gray);
      }
      if(txtCantStock.getText().isEmpty()){
          txtCantStock.setText("Ingrese la cantidad en stock");
          txtCantStock.setForeground(Color.gray);
      }
      if(txtCategoria.getText().isEmpty()){
          txtCategoria.setText("Ingrese una categoria");
          txtCategoria.setForeground(Color.gray);
      }
      if(txtUsuario.getText().isEmpty()){
          txtUsuario.setText("Ingrese el nombre del producto");
          txtUsuario.setForeground(Color.gray);
      }
      
    }//GEN-LAST:event_txtDescripcionMousePressed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (txtUsuario.getText().equals("Ingrese el nombre del producto")) {
                    txtUsuario.setText(""); 
                    txtUsuario.setForeground(Color.BLACK); 
                }
    }//GEN-LAST:event_txtUsuarioKeyPressed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtCantStock;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
